### PR TITLE
[6483] Add missing tests

### PR DESCRIPTION
**Pull request by ADubielSTX**
**Story / Bug id**: https://bugzilla.stxnext.pl/show_bug.cgi?id=6483
**Project / App**: Onboarding - Presence analyzer
**Reference person**: @piaseksp 
**Description**: Add missing tests

**Migrations**:

**Rollback**:

**New imports / dependencies**:

**Unit Tests**:

**What tests do I need to run to validate this change**:

## New or Changed JS and / or HTML Files:

### CODE REVIEW

**Comment by piasekps** [comment]
I didn't checkt this before, but Reference person: is person who work on this PR it might be one or more. Can you please add result of unitests? I would like to see result of pep8 on this file too.

**Comment by piasekps** [comment]
Please remember @ADubielSTX  that each commit should start with [number of ticket]

**Comment by ADubielSTX** [comment]
Thank you @piasekps for your sugestions. Sorry for not adding [number of ticket] I try remember it next time.

Below gist with PEP8, pylint and unittests results:
https://gist.github.com/ADubielSTX/e14dbd11af8eaf4e5a42

**Comment by piasekps** [comment]
Looks good

**Comment by ADubielSTX** [comment]
Nice

**Pull request merged**
